FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY prisma ./prisma
COPY prisma.config.ts ./

ENV DATABASE_URL="postgresql://postgres:postgres@db:5432/ihh_web"
ENV DIRECT_URL="postgresql://postgres:postgres@db:5432/ihh_web"

CMD ["npx", "prisma", "migrate", "deploy"]
